# Generated by Django 6.0 on 2026-01-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_auth_provider"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="crated_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("github", "GitHub"),
                    ("google", "Google"),
                ],
                default="email",
                max_length=20,
            ),
        ),
    ]
