# Generated by Django 6.0 on 2026-01-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_crated_at_user_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("github", "GitHub"),
                    ("email", "Email"),
                ],
                default="email",
                max_length=20,
            ),
        ),
    ]
