# Generated by Django 6.0 on 2026-01-07 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileSectionRaw",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("resume", "Resume"),
                            ("linkedin", "LinkedIn"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("skills", "Skills"),
                            ("projects", "Projects"),
                            ("experience", "Experience"),
                            ("education", "Education"),
                            ("achievements", "Achievements"),
                        ],
                        max_length=50,
                    ),
                ),
                ("raw_content", models.JSONField()),
                ("soruce_ref_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_section_raw",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["section_type", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RawGitHubData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("github_username", models.CharField(max_length=255)),
                ("profile_json", models.JSONField()),
                ("repos_json", models.JSONField()),
                ("languages_json", models.JSONField(blank=True, null=True)),
                ("readems_json", models.JSONField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_raw",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawLinkedInData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_url", models.TextField(blank=True, null=True)),
                ("raw_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkedin_raw",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawManualData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("skills", "Skills"),
                            ("projects", "Projects"),
                            ("experience", "Experience"),
                            ("education", "Education"),
                            ("achievements", "Achievements"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_raw",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawResumeData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("docx", "DOCX")], max_length=10
                    ),
                ),
                ("file_url", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_raw",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
